### ISSUE TITLE
Incompatibility with JSON Feeds

### ISSUE THREAD

**Issue by hober** [WICG/media-feeds#29]
@dbaron and I looked at this in our @w3ctag F2F this week (w3ctag/design-reviews#477).

Media Feeds are a form of syndication feed expressed in JSON. There's a [pre-existing spec](https://jsonfeed.org/version/1) for JSON Feeds, and the Media Feeds format defined here is not compatible with it. This is of course could be the case for a number of reasons, but offhand it's not clear to me why a new JSON feed format is warranted when one already exists.

**Comment by beccahughes** [comment]
Schema.org DataFeeds (which Media Feeds are based on) already exist too. In fact, for media providers they are already used to using data feeds for providing data in a server-to-server context. We decided to base Media Feeds on this standard so that providers would already be familiar and can reuse existing code.

The JSON feeds spec (while it can be extended) is also quite basic and does not provide the level of details we require. For example, it does not provide the details required for artwork (such as width, height and content attributes) and only a URL can be provided. In order to add this extra data we would need to add an extension which would not be very ergonomic and would likely lead to implementors not providing the right data e.g.

```
{
  "image": "<URL>",
  "_media": {
    "image_props": {
       width: 100,
       height: 100
     }
  }
}
```
